# Generated by Django 5.1.2 on 2024-10-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='shareable_link',
        ),
    ]
